local_costmap:
  global_frame: robot_1/odom
  robot_base_frame: robot_1/base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  rolling_window: true
  width: 3.0
  height: 3.0
  resolution: 0.05
  static_map: false
  plugins:
    - {name: static_layer,    type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

